"""
VcanTrade AI - Analytics Reporter

Generates End-of-Day (EOD) performance reports by querying the SQLite
trade ledger and autopsies tables. Outputs a clean text report that
can be saved to disk or displayed in the UI.
"""

import logging
import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional

import config

logger = logging.getLogger(__name__)

REPORTS_DIR = Path("reports")
REPORTS_DIR.mkdir(exist_ok=True)


class AnalyticsReporter:
    """
    Queries SQLite database and generates formatted EOD reports.
    Covers: Watchtower alerts, trades, grades, and CEO rejection reasons.
    """

    def __init__(self, db_path: str = "vcanitrade_ledger.db"):
        self.db_path = db_path

    def _get_connection(self):
        return sqlite3.connect(self.db_path)

    # -- public API ----------------------------------------------------------

    def generate_eod_report(self, date: Optional[datetime] = None) -> str:
        """
        Generate a complete End-of-Day report as formatted text.
        If date is None, uses today.
        """
        target_date = date or datetime.utcnow()
        day_start = target_date.replace(hour=0, minute=0, second=0, microsecond=0)
        day_end = day_start + timedelta(days=1)

        sections = [
            self._header(target_date),
            self._watchtower_summary(day_start, day_end),
            self._trades_summary(day_start, day_end),
            self._win_loss_ratio(day_start, day_end),
            self._grader_summary(day_start, day_end),
            self._ceo_rejections(day_start, day_end),
            self._footer(),
        ]

        return "\n".join(sections)

    def save_report(self, date: Optional[datetime] = None) -> Path:
        """Generate and save EOD report to reports/ directory."""
        target_date = date or datetime.utcnow()
        report_text = self.generate_eod_report(target_date)

        filename = f"EOD_{target_date.strftime('%Y-%m-%d')}.txt"
        filepath = REPORTS_DIR / filename

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_text)

        logger.info(f"EOD report saved: {filepath}")
        return filepath

    def generate_html_report(self, date: Optional[datetime] = None) -> str:
        """Generate EOD report as formatted HTML."""
        target_date = date or datetime.utcnow()
        day_start = target_date.replace(hour=0, minute=0, second=0, microsecond=0)
        day_end = day_start + timedelta(days=1)

        trades = self._get_trades(day_start, day_end)
        autopsies = self._get_autopsies(day_start, day_end)
        watchtower_count = self._get_watchtower_count(day_start, day_end)
        win_loss = self._get_win_loss(day_start, day_end)
        rejections = self._get_ceo_rejections(day_start, day_end)

        html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>VcanTrade EOD Report — {target_date.strftime("%Y-%m-%d")}</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; background: #0D1117; color: #E6EDF3; padding: 40px; }}
  h1 {{ color: #00D4FF; border-bottom: 2px solid #30363D; padding-bottom: 10px; }}
  h2 {{ color: #00D4FF; margin-top: 30px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 10px 0; }}
  th, td {{ border: 1px solid #30363D; padding: 8px 12px; text-align: left; }}
  th {{ background: #161B22; color: #00D4FF; }}
  .green {{ color: #3FB950; }}
  .red {{ color: #F85149; }}
  .dim {{ color: #8B949E; }}
  .stat {{ font-size: 24px; font-weight: bold; }}
</style>
</head>
<body>
<h1>VcanTrade AI — End of Day Report</h1>
<p class="dim">{target_date.strftime("%A, %B %d, %Y")}</p>

<h2>Watchtower Alerts</h2>
<p class="stat">{watchtower_count}</p>

<h2>Trades Executed</h2>
<p class="stat">{len(trades)}</p>

<h2>Win / Loss Ratio</h2>
<table>
  <tr><th>Wins</th><th>Losses</th><th>Win Rate</th><th>Total PnL</th></tr>
  <tr>
    <td class="green">{win_loss["wins"]}</td>
    <td class="red">{win_loss["losses"]}</td>
    <td>{win_loss["win_rate"]:.1f}%</td>
    <td class="{"green" if win_loss["total_pnl"] >= 0 else "red"}">${win_loss["total_pnl"]:.2f}</td>
  </tr>
</table>

<h2>Autopsy Grades</h2>
<table>
  <tr><th>Grade</th><th>Count</th></tr>
  {self._grade_rows_html(autopsies)}
</table>

<h2>CEO Rejection Reasons</h2>
{self._rejections_html(rejections)}

<p class="dim" style="margin-top: 40px;">Generated by VcanTrade AI Analytics Reporter</p>
</body>
</html>"""
        return html

    def save_html_report(self, date: Optional[datetime] = None) -> Path:
        """Generate and save HTML EOD report."""
        target_date = date or datetime.utcnow()
        html = self.generate_html_report(target_date)
        filename = f"EOD_{target_date.strftime('%Y-%m-%d')}.html"
        filepath = REPORTS_DIR / filename
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)
        logger.info(f"HTML EOD report saved: {filepath}")
        return filepath

    # -- report sections -----------------------------------------------------

    def _header(self, date: datetime) -> str:
        sep = "=" * 60
        return (
            f"{sep}\n"
            f"  VcanTrade AI — End of Day Report\n"
            f"  Date: {date.strftime('%A, %B %d, %Y')}\n"
            f"{sep}\n"
        )

    def _watchtower_summary(self, start: datetime, end: datetime) -> str:
        """Count of Watchtower alerts triggered today."""
        count = self._get_watchtower_count(start, end)
        return f"--- WATCHTOWER ALERTS ---\n  Total alerts triggered: {count}\n"

    def _trades_summary(self, start: datetime, end: datetime) -> str:
        """Breakdown of trades executed (manual vs auto)."""
        trades = self._get_trades(start, end)
        teacher_count = sum(1 for t in trades if t["mode"] == "TEACHER")
        auto_count = sum(1 for t in trades if t["mode"] == "AUTO")

        return (
            f"\n--- TRADES EXECUTED ---\n"
            f"  Total trades: {len(trades)}\n"
            f"  Teacher Mode (Manual): {teacher_count}\n"
            f"  Autonomous Mode (Auto): {auto_count}\n"
        )

    def _win_loss_ratio(self, start: datetime, end: datetime) -> str:
        """Win/Loss breakdown."""
        wl = self._get_win_loss(start, end)
        return (
            f"\n--- WIN / LOSS RATIO ---\n"
            f"  Wins:  {wl['wins']}\n"
            f"  Losses: {wl['losses']}\n"
            f"  Win Rate: {wl['win_rate']:.1f}%\n"
            f"  Total PnL: ${wl['total_pnl']:.2f}\n"
            f"  Avg Win: ${wl['avg_win']:.2f}\n"
            f"  Avg Loss: ${wl['avg_loss']:.2f}\n"
        )

    def _grader_summary(self, start: datetime, end: datetime) -> str:
        """Average grade and grade distribution."""
        autopsies = self._get_autopsies(start, end)
        if not autopsies:
            return f"\n--- GRADER SUMMARY ---\n  No autopsies recorded today.\n"

        grade_counts = {}
        for a in autopsies:
            g = a["overall_grade"]
            grade_counts[g] = grade_counts.get(g, 0) + 1

        # Weighted average grade
        grade_values = {"A": 4, "B": 3, "C": 2, "D": 1, "F": 0}
        total_score = sum(grade_values.get(a["overall_grade"], 2) for a in autopsies)
        avg_score = total_score / len(autopsies)
        avg_grade = "C"
        if avg_score >= 3.5:
            avg_grade = "A"
        elif avg_score >= 2.5:
            avg_grade = "B"
        elif avg_score >= 1.5:
            avg_grade = "C"
        elif avg_score >= 0.5:
            avg_grade = "D"
        else:
            avg_grade = "F"

        lines = [f"\n--- GRADER SUMMARY ---"]
        lines.append(f"  Total autopsies: {len(autopsies)}")
        lines.append(f"  Average Grade: {avg_grade}")
        lines.append(f"  Grade Distribution:")
        for grade in ["A", "B", "C", "D", "F"]:
            count = grade_counts.get(grade, 0)
            if count > 0:
                lines.append(f"    {grade}: {count}")

        return "\n".join(lines) + "\n"

    def _ceo_rejections(self, start: datetime, end: datetime) -> str:
        """Most common reasons the CEO rejected trades (HOLD signals)."""
        rejections = self._get_ceo_rejections(start, end)
        if not rejections:
            return f"\n--- CEO REJECTION REASONS ---\n  No rejections today.\n"

        lines = [f"\n--- CEO REJECTION REASONS ---"]
        lines.append(f"  Total rejections: {len(rejections)}")
        lines.append(f"  Most common reasons:")
        for reason, count in rejections[:5]:
            lines.append(f"    ({count}x) {reason[:100]}")

        return "\n".join(lines) + "\n"

    def _footer(self) -> str:
        sep = "=" * 60
        return f"{sep}\n  Generated by VcanTrade AI Analytics Reporter\n  {datetime.utcnow().strftime('%H:%M:%S UTC')}\n{sep}"

    # -- database queries ----------------------------------------------------

    def _get_watchtower_count(self, start: datetime, end: datetime) -> int:
        """Count watchtower alerts from the log (approximate — no dedicated table yet)."""
        # Watchtower alerts are logged but not stored in DB yet.
        # For now, return 0. In a future iteration, we'll add a watchtower_alerts table.
        return 0

    def _get_trades(self, start: datetime, end: datetime) -> List[Dict]:
        """Get all trades within date range."""
        conn = self._get_connection()
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT id, timestamp, asset, action, entry_price, exit_price, pnl,
                   confidence, mode, status, ai_reason
            FROM trades
            WHERE timestamp >= ? AND timestamp < ?
            ORDER BY timestamp ASC
            """,
            (start.isoformat(), end.isoformat()),
        )
        columns = [desc[0] for desc in cursor.description]
        trades = [dict(zip(columns, row)) for row in cursor.fetchall()]
        conn.close()
        return trades

    def _get_win_loss(self, start: datetime, end: datetime) -> Dict:
        """Calculate win/loss stats for date range."""
        trades = self._get_trades(start, end)
        closed = [t for t in trades if t["status"] == "CLOSED" and t["pnl"] is not None]

        wins = [t for t in closed if t["pnl"] > 0]
        losses = [t for t in closed if t["pnl"] < 0]

        total_pnl = sum(t["pnl"] for t in closed)
        win_rate = (len(wins) / len(closed) * 100) if closed else 0
        avg_win = sum(t["pnl"] for t in wins) / len(wins) if wins else 0
        avg_loss = sum(t["pnl"] for t in losses) / len(losses) if losses else 0

        return {
            "wins": len(wins),
            "losses": len(losses),
            "total_pnl": total_pnl,
            "win_rate": win_rate,
            "avg_win": avg_win,
            "avg_loss": avg_loss,
        }

    def _get_autopsies(self, start: datetime, end: datetime) -> List[Dict]:
        """Get all autopsies within date range."""
        import json

        conn = self._get_connection()
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT trade_id, asset, action, entry_price, exit_price, pnl,
                   overall_grade, technical_grade, risk_grade, explanation,
                   lessons, timestamp
            FROM autopsies
            WHERE timestamp >= ? AND timestamp < ?
            ORDER BY timestamp ASC
            """,
            (start.isoformat(), end.isoformat()),
        )
        columns = [desc[0] for desc in cursor.description]
        autopsies = []
        for row in cursor.fetchall():
            d = dict(zip(columns, row))
            try:
                d["lessons"] = json.loads(d["lessons"]) if d["lessons"] else []
            except Exception:
                d["lessons"] = []
            autopsies.append(d)
        conn.close()
        return autopsies

    def _get_ceo_rejections(self, start: datetime, end: datetime) -> List[tuple]:
        """
        Get HOLD/CLOSE signals with reasons (CEO rejections).
        Returns list of (reason, count) sorted by frequency.
        """
        conn = self._get_connection()
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT ai_reason, COUNT(*) as cnt
            FROM trades
            WHERE timestamp >= ? AND timestamp < ?
              AND action = 'HOLD'
            GROUP BY ai_reason
            ORDER BY cnt DESC
            LIMIT 10
            """,
            (start.isoformat(), end.isoformat()),
        )
        results = cursor.fetchall()
        conn.close()
        return results

    # -- HTML helpers --------------------------------------------------------

    def _grade_rows_html(self, autopsies: List[Dict]) -> str:
        grade_counts = {}
        for a in autopsies:
            g = a["overall_grade"]
            grade_counts[g] = grade_counts.get(g, 0) + 1

        rows = ""
        for grade in ["A", "B", "C", "D", "F"]:
            count = grade_counts.get(grade, 0)
            if count > 0:
                rows += f"  <tr><td>{grade}</td><td>{count}</td></tr>\n"
        return rows if rows else "  <tr><td colspan='2'>No autopsies</td></tr>"

    def _rejections_html(self, rejections: List[tuple]) -> str:
        if not rejections:
            return "<p class='dim'>No rejections today.</p>"

        rows = ""
        for reason, count in rejections[:5]:
            rows += f"  <tr><td>({count}x)</td><td>{reason[:120]}</td></tr>\n"

        return f"""<table>
  <tr><th>Count</th><th>Reason</th></tr>
  {rows}
</table>"""
